### ISSUE TITLE
Plugin suggestion

### ISSUE THREAD

**Issue by moteus** [pkulchenko/ZeroBraneEduPack#18]
I like feature like search current word in file.
It is something like search in files but do search in document
Also I found very useful hilight searched word
![image](https://user-images.githubusercontent.com/1804306/34327791-d8f99af0-e8de-11e7-8123-77d60fece8f9.png)
Some notes.
Color for selected word generates randomly so it possible do several searches at same time.
There separate command to clear all such marks (Ctrl+Alt+C in my case)

PS. this is implementation from [Ru-SciTE](https://bitbucket.org/scite-ru/scite-ru.bitbucket.org/src/ec9e67562336df397628b358c84b770064c60a9a/pack/tools/FindText.lua?at=default&fileviewer=file-view-default)

**Comment by pkulchenko** [comment]
It's probably in the this project by mistake, as it probably belongs to https://github.com/pkulchenko/ZeroBranePackage or https://github.com/pkulchenko/ZeroBraneStudio, but there is something similar in [highlightselected plugin](https://github.com/pkulchenko/ZeroBranePackage/blob/master/highlightselected.lua). I have been thinking about adding conversion from search results to multi-selection in the document.

Just a thought: you can also do a find-in-files search limited to one document (just specify the name instead of the mask, so use `foo.lua` instead of `*.lua`), but it doesn't help with conversion of the results to multi-select cursor.

I'm going to close this ticket, as it doesn't belong to EduPack, but feel free to open it in Package or Studio projects to continue the discussion if the existing alternatives are not satisfactory.
